name: PowerHouseMultiVendor CI

on:
  push:
    branches: ["main"]

jobs:
  # --- BACKEND JOB ---
  backend-process:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      - name: Install Backend Dependencies
        run: npm install

      - name: Run Backend Check
        env:
          PORT: 8000
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          APPLICATION_URL: ${{ secrets.APPLICATION_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: echo "Backend environment variables loaded successfully"

  # --- FRONTEND JOB ---
  frontend-process:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install Frontend Dependencies
        run: npm install

      - name: Vite Build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_IMG_URL: ${{ secrets.VITE_IMG_URL }}
        run: npm run build